# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: BeStarsMiMeS
author: MiMeS Collaboration

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off
  #exclude_patterns:
  #  - 'SimpleApplication/*'
